name: FarmworldReset
version: ${project.version}
main: gigaclub.farmworldreset.Main
api-version: 1.13
authors: [KevTVKevin]
description: A Farmworld Reset Plugin
website: https://GigaClub.net

commands:
  test:
    description: /test